apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-service
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/sammyCHY/Capstone_Project-E_Commerce_Platform_with_Microservices_Architecture.git
    targetRevision: main
    path: kubernetes/order-service

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true